# Settings
title: Outreach
author: University of Connecticut
email:
description: >- # this means to ignore newlines until "baseurl:"
 Outreach for UConn Department of Ecology and Evoutionary Biology
baseurl: "/"
# url: https://uconneeb.github.io/outreach
markdown: kramdown
tagline:
bannerTitle: "UConn EEB outreach<br />by HTML5 UP"
bannerTagline: Outreach site for UConn EEB
bannerDescription: This site contains outreach material developed by UConn EEB graduate students.
bannerImage: images/pic10.jpg
bannerButton: true
bannerButtonLink: index.html
contactTagline: https://eeb.uconn.edu/
copyright: Untitled

theme: minima

# Featurette
# featuretteTitle: Erat lacinia
# featuretteFirstHighlight: Portitor ullamcorper
# featuretteFirstTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
# featuretteFirstIcon: icon fa-diamond
# featuretteSecondHighlight: Sapien veroeros
# featuretteSecondTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
# featuretteSecondIcon: icon fa-paper-plane
# featuretteThirdHighlight: Quam lorem ipsum
# featuretteThirdTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
# featuretteThirdIcon: icon fa-rocket
# featuretteFourthHighlight: Sed magna finibus
# featuretteFourthTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
# featuretteFourthIcon: icon fa-signal

# Contact
address: "Ecology & Evolutionary Biology 75 N. Eagleville Road, Unit 3043 Storrs, CT 06269-3043, USA"
twitter_username: uconneeb
