# Settings
url: https://uconneeb.github.io/outreach
baseurl: /html5up-editorial
title: Editorial
tagline: by HTML5 UP
bannerTitle: "UConn EEB outreach<br />by HTML5 UP"
bannerTagline: Outreach site for UConn EEB
bannerDescription: Aenean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
bannerImage: images/pic10.jpg
bannerButton: true
bannerButtonLink: index.html
contactTagline: Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
copyright: Untitled

# Featurette
featuretteTitle: Erat lacinia
featuretteFirstHighlight: Portitor ullamcorper
featuretteFirstTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
featuretteFirstIcon: icon fa-diamond
featuretteSecondHighlight: Sapien veroeros
featuretteSecondTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
featuretteSecondIcon: icon fa-paper-plane
featuretteThirdHighlight: Quam lorem ipsum
featuretteThirdTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
featuretteThirdIcon: icon fa-rocket
featuretteFourthHighlight: Sed magna finibus
featuretteFourthTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
featuretteFourthIcon: icon fa-signal

# Contact
address: "Ecology & Evolutionary Biology 75 N. Eagleville Road, Unit 3043 Storrs, CT 06269-3043, USA"
twitter: @uconneeb
